### ISSUE TITLE
Bomber / light interceptor core / potential hangar issues dv8

### ISSUE THREAD

**Issue by Arkaiser85** [DraconisCluster/DracVerse-Issues#135]
i unhangared 3 different grids. 2 bombers and 1 interceptor. on all 3. the thrusters, gyros, survival kit and core got dismantled.
got a good look at one of em. where it looks like all those blocks were ground down in short order, all grids was also owned by nobody.
unhangaring a second interceptor of a different model had no issues.
all this in DV8 near crait.

not sure if its tied to cores or hangars, only major difference between the grids that i can see is that the grids that got dismantled all had rotating lights. and letters / numbers for decoration.
even after grinding said things off. i couldnt place a new core

**Comment by Arkaiser85** [comment]
seems to be any sort of core. for some reason stuff entering dv8 has a chance of being set to nobody wich removes all the thrusters gyros survival kits and cores.  happens on both unhangaring and jumping into dv8

**Comment by Arkaiser85** [comment]
video of how it looks and how random it seems to be when doing a restore and then copy pasting with original ownership https://www.youtube.com/watch?v=GHmFuIHNePI

**Comment by TheCodedOne** [comment]
This should be fixed next restart

**Comment by Arkaiser85** [comment]
issue still persists. 4 / 4 grids unhangared in dv8 was dismantled

**Comment by Synirrr** [comment]
Issue has been mitigated with disabling of plugin causing the issue. Coded and I will take a look at it and fix
